### ISSUE TITLE
Funny behaviour of `strength`

### ISSUE THREAD

**Issue by gsagnol** [eendebakpt/oapackage#99]
* In some of the examples, you use ``strength = 0``. Does this mean that there are no strenghth restriction at all ?

* I think that an orthogonal array of strength $t$ with factors at $s$ different levels can only exist if the number of runs $N$ is a scalar multiple of $s^t$. `Doptim()` does not complain when we ask to optimize over
the class `oapackage.arraydata_t(2, 17, 2, 3)`, for example. In the same vein, does it mean something for a design with different number of levels for each factor to have strenght $t$ ? For example, OApackage does not issue any warning when we create an `arrayclass=oapackage.arraydata_t([2,3,4], 20, 2, 3)`.

**Comment by eendebakpt** [comment]
@gsagnol `strength = 0` does indeed mean there are no restrictions on the strength. The arrays in this class would normally not be called orthogonal arrays, since the orthogonal arrays have (by the regular definition) at least strength 2.

I added a warning to the D-optimize function to warn if a non-zero strength is used.

For mixed-level arrays the strength is properly defined, the definition is a straightforward generalization of the pure-level case. The package indeed does now warn when we create the class OA([4,3,2], 20, 2, 3). I did update the code so that for this case the index of the class (computed in the `.oaindex` variable) is zero, meaning that the strength and the level specifications do not match. I also issue a warning now if the factor levels are not ordered from large to small.
